---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  playbook: test/integration/default/oneagent.yml
  ansible_config: test/ansible.cfg
  extra_vars: "@vars.yml"
  verbose: vv
  remote_user: vagrant
  chef_bootstrap_url: nil
  environment_vars:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES' # for Mac OSX compatibility

verifier:
  name: inspec

transport:
  max_ssh_sessions: 6

platforms:
  - name: debian/jessie64
  - name: windows_2012r2
    driver:
      box: tas50/windows_2012r2
      gui: false
      network:
        - ["forwarded_port", {guest: 5985, host: 5985}]
    provisioner:
      ansible_connection: winrm
      ansible_port: 5985

suites:
  - name: linux
    includes:
      - debian/jessie64
  - name: windows
    includes:
      - windows_2012r2
