---
provisioner:
  name: ansible_push
  playbook: test/integration/default/default.yml
  ansible_config: test/ansible.cfg
  verbose: vv
  remote_user: vagrant
  chef_bootstrap_url: nil

driver:
  name: vagrant

platforms:
  - name: debian/jessie64
#  - name: windows_2012r2
#    driver:
#      box: tas50/windows_2012r2
#      vagrantfile_erb: Ansible4Windows.erb

suites:
  - name: default

transport:
  max_ssh_sessions: 6
