---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  playbook: test/integration/default/oneagent.yml
  ansible_config: test/ansible.cfg
  verbose: vv
  remote_user: vagrant
  chef_bootstrap_url: nil

verifier:
  name: inspec

transport:
  max_ssh_sessions: 6

platforms:
  - name: debian/jessie64
#  - name: windows_2012r2
#    driver:
#      box: tas50/windows_2012r2

suites:
  - name: linux
    includes:
      - debian/jessie64
