---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_ansible_omnibus: true

driver:
  name: vagrant

platforms:
  - name: debian/jessie64
  - name: windows_2012r2
    driver:
      box: tas50/windows_2012r2

suites:
  - name: default

transport:
    max_ssh_sessions: 6
