---
- name: set install params
  set_fact:
    oneagent_install_params: "--set-host-group={{ dynatrace_oneagent_host_group | default('uncategorised')}} {{ dynatrace_oneagent_host_properties | join(' ') | default('') }}"
  register: oneagent_install_param

- name: Print oneagent_install_params
  debug: msg="{{ oneagent_install_params }}"

- name: Print oneagent_install_cmd
  debug: msg="{{ dynatrace_oneagent_install_cmd }}"
  
- name: Print installer line
  debug: msg="{{ dynatrace_oneagent_install_cmd }} {{ oneagent_install_params }}"
  
#- name: set install params
#  set_fact:
#    oneagent_install_params: "{{ dynatrace_oneagent_install_args }}"
#  register: oneagent_install_param

- name: install dynatrace oneagent | linux
  command: "{{ dynatrace_oneagent_install_cmd }} {{ ansible_facts.oneagent_install_params }}"
  args:
    creates: "{{ dynatrace_oneagent_install_artifact }}"
  when: ansible_system|lower == "linux" and dynatrace_oneagent_package_state != "absent"

- name: uninstall dynatrace oneAgent | linux
  command: "{{ dynatrace_oneagent_uninstall_cmd }}"
  args:
    removes: "{{ dynatrace_oneagent_install_artifact }}"
  when: ansible_system|lower == "linux" and dynatrace_oneagent_package_state == "absent"

- name: install dynatrace oneagent | windows
  win_package:
    path: "{{ dynatrace_oneagent_install_script }}"
    creates_service: "{{ dynatrace_oneagent_service_name }}"
    arguments: "{{ oneagent_install_param }} --quiet"
    state: "{{ dynatrace_oneagent_package_state }}"
  when: ansible_system|lower == "win32nt"
