---
- name: "Download Dynatrace OneAgent"
  get_url:
    url: "{{ oneagent_installer_script_url }}"
    dest: "/tmp/dynatrace-oneagent.sh"

- name: "Install Dynatrace OneAgent"
  shell: "sh /tmp/dynatrace-oneagent.sh"
  become: yes
