---
- name: "Download Dynatrace OneAgent"
  get_url:
    url: "https://{{ dynatrace_oneagent_environment_id }}.live.ruxit.com/installer/agent/unix/latest/{{ dynatrace_oneagent_tenant_token }}"
    dest: "/tmp/ruxit-Agent-Linux.sh"
  
- name: "Install Dynatrace OneAgent"
  shell: "sh /tmp/ruxit-Agent-Linux.sh"
  sudo: yes