---
 - name: Download Dynatrace OneAgent using token id
   block:
    - fail:
       msg: "The 'dynatrace_oneagent_cluster_subdomain' variable has not been set, it must point to the subdomain of your Dynatrace cluster. Please consult the documentation."
      when: (dynatrace_oneagent_cluster_subdomain is undefined) or (dynatrace_oneagent_cluster_subdomain is none) or (dynatrace_oneagent_cluster_subdomain | trim == "")
    - fail:
       msg: "The 'dynatrace_oneagent_environment_id' variable has not been set, it must contain the Dynatrace tenant id. Please consult the documentation."
      when: (dynatrace_oneagent_environment_id is undefined) or (dynatrace_oneagent_environment_id is none) or (dynatrace_oneagent_environment_id | trim == "")
    - fail:
       msg: "The 'dynatrace_oneagent_tenant_token' variable has not been set, it must contain the Dynatrace tenant token. Please consult the documentation."
      when: (dynatrace_oneagent_tenant_token is undefined) or (dynatrace_oneagent_tenant_token is none) or (dynatrace_oneagent_tenant_token | trim == "")        
    - name: "[Backward Compatibility Task] Download Dynatrace OneAgent (for Dynatrace SaaS)"
      get_url:
       url: "https://{{ dynatrace_oneagent_environment_id }}.{{ dynatrace_oneagent_cluster_subdomain }}/installer/oneagent/unix/latest/{{ dynatrace_oneagent_tenant_token }}"
       dest: "/tmp/dynatrace-oneagent.sh"
      when: ("live.dynatrace.com" == dynatrace_oneagent_cluster_subdomain) or ("live.ruxit.com" == dynatrace_oneagent_cluster_subdomain) or ("sprint.dynatracelabs.com" == dynatrace_oneagent_cluster_subdomain)
    - name: "[Backward Compatibility Task] Download Dynatrace OneAgent (for Dynatrace Managed)"
      get_url:
       url: "https://{{ dynatrace_oneagent_cluster_subdomain }}/e/{{ dynatrace_oneagent_environment_id }}/installer/agent/unix/latest/{{ dynatrace_oneagent_tenant_token }}"
       dest: "/tmp/dynatrace-oneagent.sh"
      when: ("live.dynatrace.com" != dynatrace_oneagent_cluster_subdomain) and ("live.ruxit.com" != dynatrace_oneagent_cluster_subdomain)
   when: (oneagent_installer_script_url is undefined) or (oneagent_installer_script_url is none) or (oneagent_installer_script_url | trim == "")
   
 - name: Download Dynatrace OneAgent using installer script url
   block:
   - fail:
      msg: "The 'oneagent_installer_script_url' variable has not been set, it must contain the Dynatrace OneAgent Installer Script URL. Please consult the documentation."
     when: (oneagent_installer_script_url is undefined) or (oneagent_installer_script_url is none) or (oneagent_installer_script_url | trim == "")
   - name: "Download Dynatrace OneAgent"
     get_url:
      url: "{{ oneagent_installer_script_url }}"
      dest: "/tmp/dynatrace-oneagent.sh"    
   when: (oneagent_installer_script_url is defined) and (oneagent_installer_script_url is not none)
    
 - name: "Install Dynatrace OneAgent"
   shell: "sh /tmp/dynatrace-oneagent.sh"
   become: yes
