---
- name: Load variables based on OS
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: Fail if Dynatrace OneAgent is already installed
  stat:
    path: "{{ dynatrace_oneagent_install_artifact }}"
  register: agent_installed
  failed_when: agent_installed.stat.exists == True

- name: Use multi-platform download
  import_tasks: multi_platform.yml
  when:
    - dynatrace_oneagent_cluster_subdomain is defined
    - dynatrace_oneagent_environment_id is defined
    - dynatrace_oneagent_tenant_token is defined

- name: Install Dynatrace OneAgent
  import_tasks: install.yml
