---
- name: "[Multi-Platform] Download Dynatrace OneAgent (for Dynatrace SaaS)"
  get_url:
    url: "https://{{ dynatrace_oneagent_environment_id }}.{{ dynatrace_oneagent_cluster_subdomain }}/api/v1/deployment/installer/agent/{{ dynatrace_oneagent_install_url_key }}/default/latest?Api-Token={{ dynatrace_oneagent_tenant_token }}&arch=x86&flavor=default"
    dest: "{{ dynatrace_oneagent_install_script }}"
    force: yes
  when: dynatrace_oneagent_cluster_subdomain == "live.dynatrace.com" or
        dynatrace_oneagent_cluster_subdomain == "sprint.dynatracelabs.com" or
        dynatrace_oneagent_cluster_subdomain == "live.ruxit.com"

- name: "[Multi-Platform] Download Dynatrace OneAgent (for Dynatrace Managed)"
  get_url:
    url: "https://{{ dynatrace_oneagent_cluster_subdomain }}/e/{{ dynatrace_oneagent_environment_id }}/api/v1/deployment/installer/agent/{{ dynatrace_oneagent_install_url_key }}/default/latest?Api-Token={{ dynatrace_oneagent_tenant_token }}&arch=x86&flavor=default"
    dest: "{{ dynatrace_oneagent_install_script }}"
    force: yes
  when: dynatrace_oneagent_cluster_subdomain is search("dynatrace-managed.com")
